services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:3000'
    volumes:
      - './frontend:/opt/app'
    environment:
      - CI=true
    restart: always
  backend:
    build:
      context: ./backend
    ports:
      - '4040:4040'
    volumes:
      - './backend:/opt/app'
    restart: always
